### ISSUE TITLE
Sprint#1 - Vídeo (gravação do Login + CRUD)  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [flpoli/YAD188-G13-EasySales#23]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente****  o vídeo produzido, e que será apresentado em aula

**Comment by alexjacket** [comment]
video 1 [https://fatecspgov-my.sharepoint.com/✌️/g/personal/alexandre_delgado01_fatec_sp_gov_br/EX1aBBUHxjZPu4-Jk3swpUIBcvigfW547AlTysbmW25B2Q?e=pitzIb](https://fatecspgov-my.sharepoint.com/:v:/g/personal/alexandre_delgado01_fatec_sp_gov_br/EX1aBBUHxjZPu4-Jk3swpUIBcvigfW547AlTysbmW25B2Q?e=pitzIb)

v'ideo 2 [https://fatecspgov-my.sharepoint.com/✌️/g/personal/alexandre_delgado01_fatec_sp_gov_br/EVCJiS99NutOqsgE9oPY6r4BQxvU3uw6EF5JV63_-XGrPw?e=CdQBiE](https://fatecspgov-my.sharepoint.com/:v:/g/personal/alexandre_delgado01_fatec_sp_gov_br/EVCJiS99NutOqsgE9oPY6r4BQxvU3uw6EF5JV63_-XGrPw?e=CdQBiE)
